### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'context'

### ISSUE THREAD

**Issue by GenTxt** [WeazelDev/AITextGeneratorFront#2]
Hello again.

Thanks for the replies and updated code. Trained a a gpt2 small model using the 'eval' folder .json files. Next 'run_backend.py  loads supplied NER model and small gpt2 model:

gpt2_model = GPT2LMHeadModel.from_pretrained('models/gpt2-small-eval-fp16')
gpt2_tokenizer = GPT2Tokenizer.from_pretrained('models/gpt2-small-eval-fp16')
gpt2_flexible_model = FlexibleGPT2(gpt2_model, gpt2_tokenizer, DEFAULT_DECODING_STRATEGY)
self.gen_model = TextGeneration(gpt2_flexible_model, use_context=True)

Next have 'AITextGeneratorFront' running http://localhost:8080/ 
Main page opens. Click to 'Editor' page, write or copy some text.
Highlight the next and the NER model selects, for example, the name 'John' but when I click generate the selected text is deleted. No options appear in the right column

Error message in the 'run_backend.py' terminal window is:

TypeError: __init__() got an unexpected keyword argument 'context'

Any idea on how to fix this? Would like to test custom .json files but it's not working with the defaults.

Thanks

  
have 'AITextGeneratorFront' running http://localhost:8080/Main page opens

**Comment by WeazelDev** [comment]
Again, i'm afraid this is still unfinished business!
But be reassured because we are actively working on this project and all of it should be working entirely (the whole data preparation / training / eval / webservice pipeline) in less than two weeks or so.

I will let this issue open so that I don't forget about the error you encountered, but recent evolutions in the training and inference part require a certain rework of the backend. Moreover, i want to uncouple the computing instance (running the big models) and the serving instance (serving the frontend and handling small events like sharing features), which will have an impact on front and backend.

And yes, there is an issue with text being deleted if there is no answer from the backend server, or a wrong answer (an exception on the backend gives no/wrong answer to the front).

Thanks for your interest, and I hope we can fix all of this as soon as possible ! Don't hesitate to contact me personally at contact@thomas-lamson.com, if you want to discuss some things more thoroughly!
